ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS attachment_name TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS attachment_mime TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS attachment_size INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS attachment_storage_name TEXT NOT NULL DEFAULT '';
